name: Sync Upstream

permissions:
  contents: write

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows you to trigger it manually from the Actions tab

jobs:
  sync_with_upstream:
    name: Sync Main with Upstream
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main             # Checkout your fork's main branch
          fetch-depth: 0        # Fetch full history for merges

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          # REQUIRED: The upstream repo you want to sync from
          upstream_sync_repo: DragnaCarta/Curse-of-Strahd-Reloaded
          upstream_sync_branch: main
          # REQUIRED: Secret for pushing changes to your fork
          target_repo_token: ${{ secrets.PAT_TOKEN }}
          
          # Set to 'false' to actually perform the sync. 
          # Set to 'true' to run a test without pushing changes.
          test_mode: false
